// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://godzcghirjicvmzkndgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZHpjZ2hpcmppY3ZtemtuZGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTY4MDcsImV4cCI6MjA2ODE3MjgwN30.IIvRHN03xP434Ez3licYuWWKNbtB69yqQTkZNnVemBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});